name = "darkhub-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SCRIPTS_KV"
id = "672faa2b8aff4b4c9507fd3315fe4a3c"

[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "1bc159b03e104910998d48137da71154"

[[kv_namespaces]]
binding = "RATELIMIT_KV"
id = "e1e08350f467479383bd3ff18434e732"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "368f4c219c3e49fabfe9223cc359f5f1"

[[kv_namespaces]]
binding = "NONCES_KV"
id = "3fc11096561c472cb220fc9ffd43314e"

[vars]
FRONTEND_ORIGIN    = "https://Themiga.github.io"
OAUTH_CALLBACK_URL = "https://Themiga.github.io/darkhub/callback.html"
